# Generated by Django 4.0.6 on 2022-07-30 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_course_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='update_add',
            new_name='update_at',
        ),
    ]
