# Generated by Django 4.0.6 on 2022-07-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_update_add_course_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
