# Generated by Django 4.0.6 on 2022-08-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_studentfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafffeedback',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentfeedback',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
