# Generated by Django 4.0.6 on 2022-07-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_staff_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='middle_name',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
